### PR TITLE
add new story!

### PR DESCRIPTION
**Pull request by Shawnmflanigan**
We are working on a group project for a full stack bootcamp and we are using your API. This is just a test to see if this works so...if it does, we will be adding a number of stories to your template. We are trying to use your template so please let me know if I've done something that doesn't work.

Thanks! 
-Shawn Flanigan
feel free to reach out to me at shawnmflanigan@gmail.com

### CODE REVIEW

**Comment by HermanFassett** [comment]
Hey, thanks for adding this. Looks like you're missing a comma after the title

**Comment by HermanFassett** [comment]
Thanks, that should work.
The heroku demo site won't be updated yet because it's running an old deploy stack that I tried quickly to update but I'll have to spend more time upgrading later today.

**Comment by HermanFassett** [comment]
I've upgrade so it is deployed now, though only api is working, the demo page has some issues with the upgrade that I can't take care of atm.

**Comment by Shawnmflanigan** [comment]
Awesome! I had just noticed it while fixing some of the styling on our page.

Thanks!

**Pull request merged**
